version: 2

updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      spring:
        patterns:
          - org.springframework*

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-tooling:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
