services:
  - type: web
    name: pagina-investimentos-demo
    runtime: docker
    plan: free
    region: virginia
    branch: main
    autoDeployTrigger: checksPass
    healthCheckPath: /actuator/health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: demo
      - key: SERVER_ADDRESS
        value: 0.0.0.0
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC
