spring.application.name=portfolio-api
server.port=${PORT:8080}
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

info.app.name=Planejador de Carteira API
info.app.version=0.1.0
